### ISSUE TITLE
Exception when callee hangs up outbound call

### ISSUE THREAD

**Issue by ghjansen** [RestComm/olympus#100]
When `alice` calls to an RCML application that dials to `bob`, the call is correctly stablished, but when `bob` hangs up, the following exception occurs preventing to send the BYE message:
```
2017-21-03 10:40:49.489 PrivateJainSipCallConnector:close(): catched exception:TypeError: Cannot read property 'createRequest' of null 

Stack trace: 
    at commonLog (https://54.90.157.242/olympus/resources/js/mobicents-libs/WebRTComm.js:4886:10)
    at Object.console.error (https://54.90.157.242/olympus/resources/js/mobicents-libs/WebRTComm.js:4959:4)
    at PrivateJainSipCallConnector.close (https://54.90.157.242/olympus/resources/js/mobicents-libs/WebRTComm.js:534:12)
    at WebRTCommCall.hangup (https://54.90.157.242/olympus/resources/js/mobicents-libs/WebRTComm.js:2236:20)
    at Arguments.<anonymous> (https://54.90.157.242/olympus/resources/js/mobicents-libs/WebRTComm.js:2403:10)
    at successCallbackWrapper (https://54.90.157.242/olympus/resources/js/adapter/adapter.js:291:18)
```
Environment
--
- latest Restcomm
- latest Olympus 2.0
- patched version of JSR 309 connector
- XMS

Scenario
--
1 - `alice` calls RCML application
2 - `VoiceInterpreter` creates an outbound call to `bob`
3 - `bob` accepts the call and the call is correctly stablished
4 - `bob` hangs up the call
The error happens on `4` leaving `alice` with the call connected

RCML application:
```
<Response>
    <Say>This application is a test for issue 19 41. Calling bob now.</Say>
    <Dial action="controller?target=start.step2.actionhandler">
        <Client>bob</Client>
    </Dial>
</Response>
```
```
<Response>
    <Say>Call executed with success.</Say>
</Response>
```
Console log from Chrome/Olympus: [54.90.157.242-1490103657235.txt](https://github.com/RestComm/olympus/files/859032/54.90.157.242-1490103657235.txt)
Restcomm log: [restcomm-log.txt](https://github.com/RestComm/olympus/files/859096/restcomm-log.txt)

**Comment by atsakiridis** [comment]
Turns out to be [webrtcomm issue](https://github.com/RestComm/webrtcomm/issues/94)
