### ISSUE TITLE
Cannot read property 'timerProm' of undefined error

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/olympus#110]
Scenario:
- Register alice and bob from 2 tabs in chrome
- Make P2P call from alice to bob
- Decline the call from bob

At that point I get:
```
WebRTComm.js:4888 2017-27-04 11:14:35.179 ERROR TypeError: Cannot read property 'timerProm' of undefined
    at https://cloud.restcomm.com/olympus/resources/js/controllers/home.js:572:39
    at Scope.$eval (https://cloud.restcomm.com/olympus/lib/angular/angular.js:14388:28)
    at Scope.$apply (https://cloud.restcomm.com/olympus/lib/angular/angular.js:14487:23)
    at https://cloud.restcomm.com/olympus/resources/js/controllers/home.js:558:12
    at Scope.$broadcast (https://cloud.restcomm.com/olympus/lib/angular/angular.js:14707:28)
    at Object.onWebRTCommCallClosedEvent (https://cloud.restcomm.com/olympus/resources/js/services.js:54:16)
    at https://cloud.restcomm.com/olympus/resources/js/mobicents-libs/WebRTComm.js:2552:24 
```

Tested on cloud, Restcomm Connect version: 8.2.0.1505

**Comment by ammendonca** [comment]
Fixed with 4cf3ba7d663c4a293ac2c1713aace3c54087a69d.
